version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - "/home/ankit/Ankit/jenkins/jenkins_data:/var/jenkins_home"
    networks:
      - net
networks:
  net:
